//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoClicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Active Macro: {_activeMacroName} (Tap to change) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string activemacro {
            get {
                return ResourceManager.GetString("activemacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active Macro: {_activeMacroName}* (Tap to change) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string activemacro_unsaved {
            get {
                return ResourceManager.GetString("activemacro_unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm Delete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ask_confirmdel {
            get {
                return ResourceManager.GetString("ask_confirmdel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete macro {selectedName}? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ask_delmacro {
            get {
                return ResourceManager.GetString("ask_delmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a new macro name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ask_enternewmacro {
            get {
                return ResourceManager.GetString("ask_enternewmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Macro benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ask_savemacrotitle {
            get {
                return ResourceManager.GetString("ask_savemacrotitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created Macro benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string createdmacro {
            get {
                return ResourceManager.GetString("createdmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new Macro benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string createmacro_title {
            get {
                return ResourceManager.GetString("createmacro_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string defaultmacro {
            get {
                return ResourceManager.GetString("defaultmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DISCARD benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string discard {
            get {
                return ResourceManager.GetString("discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string editdesc {
            get {
                return ResourceManager.GetString("editdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name or Description cannot be empty. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_emptynamedesc {
            get {
                return ResourceManager.GetString("err_emptynamedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A macro with this name already exists! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_existmacroname {
            get {
                return ResourceManager.GetString("err_existmacroname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incompatible Version: #VER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_incompatibleversion {
            get {
                return ResourceManager.GetString("err_incompatibleversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please type a valid position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_invalid_pos {
            get {
                return ResourceManager.GetString("err_invalid_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A macro with this name already exists. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_macroexists {
            get {
                return ResourceManager.GetString("err_macroexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please type a name for macro. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_nullnamecreatemacro {
            get {
                return ResourceManager.GetString("err_nullnamecreatemacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_title {
            get {
                return ResourceManager.GetString("err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold Duration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string holddur_groupbox {
            get {
                return ResourceManager.GetString("holddur_groupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkey benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string htk {
            get {
                return ResourceManager.GetString("htk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a macro. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string info_selectmacro {
            get {
                return ResourceManager.GetString("info_selectmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_groupbox {
            get {
                return ResourceManager.GetString("interval_groupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 seconds = 1000 milliseconds
        ///1 minute = 60 seconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_info {
            get {
                return ResourceManager.GetString("interval_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   milliseconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_millis {
            get {
                return ResourceManager.GetString("interval_millis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbldesc {
            get {
                return ResourceManager.GetString("lbldesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblname {
            get {
                return ResourceManager.GetString("lblname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro List benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string macrolist {
            get {
                return ResourceManager.GetString("macrolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Selection benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string macroselectiontitle {
            get {
                return ResourceManager.GetString("macroselectiontitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No description benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string nodesc {
            get {
                return ResourceManager.GetString("nodesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_clicktype {
            get {
                return ResourceManager.GetString("opt_clicktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_cm_click {
            get {
                return ResourceManager.GetString("opt_cm_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hold benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_cm_hold {
            get {
                return ResourceManager.GetString("opt_cm_hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Mod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_cmod {
            get {
                return ResourceManager.GetString("opt_cmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_double {
            get {
                return ResourceManager.GetString("opt_ct_double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quadruple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_quadruple {
            get {
                return ResourceManager.GetString("opt_ct_quadruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_single {
            get {
                return ResourceManager.GetString("opt_ct_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_triple {
            get {
                return ResourceManager.GetString("opt_ct_triple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_gb {
            get {
                return ResourceManager.GetString("opt_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_lang {
            get {
                return ResourceManager.GetString("opt_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_left {
            get {
                return ResourceManager.GetString("opt_mb_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_mid {
            get {
                return ResourceManager.GetString("opt_mb_mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_right {
            get {
                return ResourceManager.GetString("opt_mb_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse Button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_msbtn {
            get {
                return ResourceManager.GetString("opt_msbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_current {
            get {
                return ResourceManager.GetString("pos_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_gb {
            get {
                return ResourceManager.GetString("pos_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified Location benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_spec {
            get {
                return ResourceManager.GetString("pos_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat Until Stopped benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_forever {
            get {
                return ResourceManager.GetString("rep_forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_gb {
            get {
                return ResourceManager.GetString("rep_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   times benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_times {
            get {
                return ResourceManager.GetString("rep_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Clicker benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t create macro named &quot;DEFAULT&quot;. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_cantcreatedef {
            get {
                return ResourceManager.GetString("wrn_cantcreatedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t delete default settings. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_cantdeldef {
            get {
                return ResourceManager.GetString("wrn_cantdeldef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t edit default settings. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_canteditdef {
            get {
                return ResourceManager.GetString("wrn_canteditdef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default macro can&apos;t be found, adding one. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_cantfounddef {
            get {
                return ResourceManager.GetString("wrn_cantfounddef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid hotkey setting. Defaulting to F6. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_invalidhtk {
            get {
                return ResourceManager.GetString("wrn_invalidhtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a macro to delete. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_selectmacrodel {
            get {
                return ResourceManager.GetString("wrn_selectmacrodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wrn_title {
            get {
                return ResourceManager.GetString("wrn_title", resourceCulture);
            }
        }
    }
}
