//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoClicker.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoClicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Click this to cancel setting hotkey benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cancel_setting_htk {
            get {
                return ResourceManager.GetString("cancel_setting_htk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hotkey set to #HTK successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string done_htkset_txt {
            get {
                return ResourceManager.GetString("done_htkset_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can&apos;t assign Ctrl, Shift and Alt keys. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_assignmodifier_txt {
            get {
                return ResourceManager.GetString("err_assignmodifier_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please type a valid position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_invalid_pos {
            get {
                return ResourceManager.GetString("err_invalid_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string err_title {
            get {
                return ResourceManager.GetString("err_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_groupbox {
            get {
                return ResourceManager.GetString("interval_groupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hours benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_hours {
            get {
                return ResourceManager.GetString("interval_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   milliseconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_millis {
            get {
                return ResourceManager.GetString("interval_millis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   minutes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_mins {
            get {
                return ResourceManager.GetString("interval_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   seconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interval_secs {
            get {
                return ResourceManager.GetString("interval_secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click Type benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_clicktype {
            get {
                return ResourceManager.GetString("opt_clicktype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_double {
            get {
                return ResourceManager.GetString("opt_ct_double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quadruple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_quadruple {
            get {
                return ResourceManager.GetString("opt_ct_quadruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_single {
            get {
                return ResourceManager.GetString("opt_ct_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_ct_triple {
            get {
                return ResourceManager.GetString("opt_ct_triple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_gb {
            get {
                return ResourceManager.GetString("opt_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_lang {
            get {
                return ResourceManager.GetString("opt_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_left {
            get {
                return ResourceManager.GetString("opt_mb_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mid benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_mid {
            get {
                return ResourceManager.GetString("opt_mb_mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_mb_right {
            get {
                return ResourceManager.GetString("opt_mb_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse Button benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string opt_msbtn {
            get {
                return ResourceManager.GetString("opt_msbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_current {
            get {
                return ResourceManager.GetString("pos_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_gb {
            get {
                return ResourceManager.GetString("pos_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified Location benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pos_spec {
            get {
                return ResourceManager.GetString("pos_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat Until Stopped benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_forever {
            get {
                return ResourceManager.GetString("rep_forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_gb {
            get {
                return ResourceManager.GetString("rep_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   times benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string rep_times {
            get {
                return ResourceManager.GetString("rep_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SET HOTKEY benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sethtk {
            get {
                return ResourceManager.GetString("sethtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   START benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STOP benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Clicker benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Clicker (WAITING FOR HOTKEY) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string title_waiting {
            get {
                return ResourceManager.GetString("title_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAITING... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
    }
}
